site_name: HSHL Open Source Lab
edit_uri: https://github.com/HSHL/OSL/edit/main/docs
theme:
    name: material
    features:
      - content.action.edit
    palette:
      - scheme: default
        toggle: 
            icon: material/weather-night
            name: Dark Mode
      - scheme: slate
        toggle: 
            icon: material/weather-sunny
            name: Light Mode
