site_name: HSHL Open Source Lab
edit_uri: https://github.com/HSHL/OSL/edit/main/docs
nav:
  - Home: index.md
  - Projects & Resources: projects.md
  - Impressum: impressum.md
theme:
    name: material
    features:
      - content.action.edit
    palette:
      - scheme: default
        toggle: 
            icon: material/weather-night
            name: Dark Mode
      - scheme: slate
        toggle: 
            icon: material/weather-sunny
            name: Light Mode
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
